### ISSUE TITLE
RingQ.exe被360卫士查杀了

### ISSUE THREAD

**Issue by chz2008** [T4y1oR/RingQ#1]
RingQ.exe被360卫士查杀了。能提供源码吗

**Comment by T4y1oR** [comment]
暂不开源，已更新。360报毒QVM202 更换图标资源 添加签名操作.. 即可

**Comment by chz2008** [comment]
我更换了图标  结果也杀

**Comment by T4y1oR** [comment]
Releases新增原编译main.exe文件，方便大家自定义修改降熵，如持续出现QVM202 后续考虑发布专项脚本bypass QVM202

**Comment by chz2008** [comment]
![00445F1C](https://github.com/T4y1oR/RingQ/assets/41458106/8c93081c-7bea-4996-b7dd-724ac4db0fe2)
