### ISSUE TITLE
6.4已经用不了了吗，下载下create完后执行Ring.exe无反应

### ISSUE THREAD

**Issue by shenmirenaa** [T4y1oR/RingQ#18]

**Comment by 3tefanie** [comment]
测试最新版fscan,执行RingQ.exe过后确实会一直卡住

**Comment by T4y1oR** [comment]
<img width="1059" alt="image" src="https://github.com/T4y1oR/RingQ/assets/85985129/c4fb5350-9c36-4f09-bec8-c55f765be75c">
刚测试正常 CMD页面卡住 尝试按下回车

**Comment by 3tefanie** [comment]
一开始就尝试按过回车，没反应。看了师傅的动图，我重新生成了一个，也多次测试按了回车，只有一次成功显示了fscan的info信息
![image](https://github.com/T4y1oR/RingQ/assets/70634340/29cfcabd-5a7e-4a22-b772-2331e5d9ad22)

其它测试情况还是经常卡住，有点玄学。
![image](https://github.com/T4y1oR/RingQ/assets/70634340/0b1ee12b-927d-4b64-ba9d-25b051bdac14)

**Comment by Summer961211** [comment]
我也是 执行不下去

**Comment by T4y1oR** [comment]
**BUG 已修复，可以下载最新版本直接使用 或者 下载源码自行编译。**
@3tefanie 
@Summer961211 
@shenmirenaa

**Comment by ymbzd** [comment]
刚测试了…还是会卡住

**Comment by T4y1oR** [comment]
> 刚测试了…还是会卡住

麻烦提供一下环境信息

**Comment by ymbzd** [comment]
主机名:           WOWO
OS 名称:          Microsoft Windows 10 企业版
OS 版本:          10.0.17763 暂缺 Build 17763
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     DESKTOP
注册的组织:       暂缺
产品 ID:          00329-10291-23239-AA494
初始安装日期:     2020/3/24, 11:12:05
系统启动时间:     2024/6/5, 9:17:13
系统制造商:       LENOVO
系统型号:         20U2SA4K00
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1803 Mhz
BIOS 版本:        LENOVO R17ET29W (1.12 ), 2021/5/5
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     16,135 MB
可用的物理内存:   8,522 MB
虚拟内存: 最大值: 32,519 MB
虚拟内存: 可用:   23,198 MB
虚拟内存: 使用中: 9,321 MB
页面文件位置:     C:\pagefile.sys
域:               DEVIL
登录服务器:       \\WOWO
修补程序:         安装了 14 个修补程序。
                  [01]: KB4601555
                  [02]: KB4486153
                  [03]: KB4486155
                  [04]: KB4494174
                  [05]: KB4512577
                  [06]: KB4523204
                  [07]: KB4535680
                  [08]: KB4537759
                  [09]: KB4539571
                  [10]: KB4549947
                  [11]: KB4577586
                  [12]: KB4589208
                  [13]: KB4601393
                  [14]: KB4601345
网卡:             安装了 12 个 NIC。
                  [01]: Intel(R) Ethernet Connection (10) I219-V
                      连接名:      以太网 2
                      状态:        媒体连接已中断
                  [02]: Realtek RTL8852AE WiFi 6 802.11ax PCIe Adapter
                      连接名:      WLAN 3
                      启用 DHCP:   是
                      DHCP 服务器: 172.100.30.254
                      IP 地址
                        [01]: 172.100.30.44
                  [03]: Gateway NC Adapter
                      连接名:      以太网 4
                      状态:        媒体连接已中断
                  [04]: VMware Virtual Ethernet Adapter for VMnet1
                      连接名:      VMware Network Adapter VMnet1
                      启用 DHCP:   否
                      IP 地址
                        [01]: 192.168.190.1
                        [02]: fe80::1104:b501:6bea:4222
                  [05]: VMware Virtual Ethernet Adapter for VMnet8
                      连接名:      VMware Network Adapter VMnet8
                      启用 DHCP:   否
                      IP 地址
                        [01]: 192.168.80.1
                        [02]: fe80::a0b4:ab6e:473e:e31c
                  [06]: Microsoft KM-TEST Loopback Adapter
                      连接名:      Npcap Loopback Adapter
                      启用 DHCP:   是
                      DHCP 服务器: 255.255.255.255
                      IP 地址
                        [01]: 169.254.181.219
                        [02]: fe80::e5cf:c3f5:bfd4:b5db
                  [07]: Sangfor SSL VPN CS Support System VNIC
                      连接名:      以太网 5
                      状态:        媒体连接已中断
                  [08]: Array Networks TAP-Windows Adapter
                      连接名:      本地连接
                      状态:        媒体连接已中断
                  [09]: Array Networks SSL VPN Adapter
                      连接名:      以太网 7
                      状态:        没有硬件
                  [10]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                      连接名:      以太网 8
                      状态:        没有硬件
                  [11]: iNode VPN Virtual NIC
                      连接名:      以太网 9
                      状态:        媒体连接已中断
                  [12]: Hyper-V Virtual Ethernet Adapter
                      连接名:      vEthernet (Default Switch)
                      启用 DHCP:   否
                      IP 地址
                        [01]: 172.17.125.49
                        [02]: fe80::51fb:ae2a:fee2:93d4
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是

**Comment by T4y1oR** [comment]
> 主机名: WOWO OS 名称: Microsoft Windows 10 企业版 OS 版本: 10.0.17763 暂缺 Build 17763 OS 制造商: Microsoft Corporation OS 配置: 独立工作站 OS 构建类型: Multiprocessor Free 注册的所有人: DESKTOP 注册的组织: 暂缺 产品 ID: 00329-10291-23239-AA494 初始安装日期: 2020/3/24, 11:12:05 系统启动时间: 2024/6/5, 9:17:13 系统制造商: LENOVO 系统型号: 20U2SA4K00 系统类型: x64-based PC 处理器: 安装了 1 个处理器。 [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1803 Mhz BIOS 版本: LENOVO R17ET29W (1.12 ), 2021/5/5 Windows 目录: C:\Windows 系统目录: C:\Windows\system32 启动设备: \Device\HarddiskVolume1 系统区域设置: zh-cn;中文(中国) 输入法区域设置: zh-cn;中文(中国) 时区: (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐 物理内存总量: 16,135 MB 可用的物理内存: 8,522 MB 虚拟内存: 最大值: 32,519 MB 虚拟内存: 可用: 23,198 MB 虚拟内存: 使用中: 9,321 MB 页面文件位置: C:\pagefile.sys 域: DEVIL 登录服务器: \WOWO 修补程序: 安装了 14 个修补程序。 [01]: KB4601555 [02]: KB4486153 [03]: KB4486155 [04]: KB4494174 [05]: KB4512577 [06]: KB4523204 [07]: KB4535680 [08]: KB4537759 [09]: KB4539571 [10]: KB4549947 [11]: KB4577586 [12]: KB4589208 [13]: KB4601393 [14]: KB4601345 网卡: 安装了 12 个 NIC。 [01]: Intel(R) Ethernet Connection (10) I219-V 连接名: 以太网 2 状态: 媒体连接已中断 [02]: Realtek RTL8852AE WiFi 6 802.11ax PCIe Adapter 连接名: WLAN 3 启用 DHCP: 是 DHCP 服务器: 172.100.30.254 IP 地址 [01]: 172.100.30.44 [03]: Gateway NC Adapter 连接名: 以太网 4 状态: 媒体连接已中断 [04]: VMware Virtual Ethernet Adapter for VMnet1 连接名: VMware Network Adapter VMnet1 启用 DHCP: 否 IP 地址 [01]: 192.168.190.1 [02]: fe80::1104:b501:6bea:4222 [05]: VMware Virtual Ethernet Adapter for VMnet8 连接名: VMware Network Adapter VMnet8 启用 DHCP: 否 IP 地址 [01]: 192.168.80.1 [02]: fe80::a0b4:ab6e:473e:e31c [06]: Microsoft KM-TEST Loopback Adapter 连接名: Npcap Loopback Adapter 启用 DHCP: 是 DHCP 服务器: 255.255.255.255 IP 地址 [01]: 169.254.181.219 [02]: fe80::e5cf:c3f5:bfd4:b5db [07]: Sangfor SSL VPN CS Support System VNIC 连接名: 以太网 5 状态: 媒体连接已中断 [08]: Array Networks TAP-Windows Adapter 连接名: 本地连接 状态: 媒体连接已中断 [09]: Array Networks SSL VPN Adapter 连接名: 以太网 7 状态: 没有硬件 [10]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64 连接名: 以太网 8 状态: 没有硬件 [11]: iNode VPN Virtual NIC 连接名: 以太网 9 状态: 媒体连接已中断 [12]: Hyper-V Virtual Ethernet Adapter 连接名: vEthernet (Default Switch) 启用 DHCP: 否 IP 地址 [01]: 172.17.125.49 [02]: fe80::51fb:ae2a:fee2:93d4 Hyper-V 要求: 虚拟机监视器模式扩展: 是 固件中已启用虚拟化: 是 二级地址转换: 是 数据执行保护可用: 是

本地测试Windows 10 企业版和Windows Server 2012 均正常，你可以下载源码自己编译下。
<img width="1168" alt="image" src="https://github.com/T4y1oR/RingQ/assets/85985129/978090d2-7cd3-4e35-86e1-58a3c7bb6afa">
<img width="1183" alt="image" src="https://github.com/T4y1oR/RingQ/assets/85985129/4d87c1f7-a383-4eda-b4ba-e0ece15f9e42">
