### ISSUE TITLE
已被360拦截

### ISSUE THREAD

**Issue by allblue147** [T4y1oR/RingQ#20]
![image](https://github.com/T4y1oR/RingQ/assets/48712195/1d79adad-9db2-4100-ae07-40f13ac0f2a1)
师傅，能不能优化下 好像被拦截了

**Comment by T4y1oR** [comment]
已更新，QVM202 报毒看一下README.md
<img width="204" alt="image" src="https://github.com/T4y1oR/RingQ/assets/85985129/9237fea8-732d-46a5-aaef-c7e1a3cd355e">
