### ISSUE TITLE
060801已被火绒检测

### ISSUE THREAD

**Issue by BoBppy** [T4y1oR/RingQ#23]
![image](https://github.com/T4y1oR/RingQ/assets/46050967/5574b731-6d21-497d-8416-d3ad02038cb1)

**Comment by yinsel** [comment]
> ![image](https://private-user-images.githubusercontent.com/46050967/337734693-5574b731-6d21-497d-8416-d3ad02038cb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzY1MjAsIm5iZiI6MTcxNzkzNjIyMCwicGF0aCI6Ii80NjA1MDk2Ny8zMzc3MzQ2OTMtNTU3NGI3MzEtNmQyMS00OTdkLTg0MTYtZDNhZDAyMDM4Y2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MGZjN2ZkYmRjOTMwMDEzZGFkYjg0NWE5MWMwM2NjNDRjN2NkOWY2MjExNjlhNDNhNmNlMTA4MGNjZTNkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YVv64V-E33IAnOQnK31ziD6DQsuBpkCs21w4A2bg5gA)

工具被检测很正常吗，请查看生成的exe是否被检测

**Comment by T4y1oR** [comment]
已更新
