### ISSUE TITLE
大佬们这个显示登陆错误是什么意思？

### ISSUE THREAD

**Issue by yeuwie** [T4y1oR/RingQ#27]
已完成 8/9 [-] ftp 192.168.1.1:21 ftp Aa123456! 421 Login incorrect.
已完成 8/9 [-] ftp 192.168.1.1:21 admin a123123 421 Login incorrect.
已完成 8/9 [-] ftp 192.168.1.1:21 www abc123 421 Login incorrect.
已完成 8/9 [-] ftp 192.168.1.1:21 web 666666 421 Login incorrect.
已完成 8/9 [-] ftp 192.168.1.1:21 root P@ssw0rd 421 Login incorrect.
已完成 8/9 [-] ftp 192.168.1.1:21 db db123 421 Login incorrect.
已完成 8/9 [-] ftp 192.168.1.1:21 wwwroot 111111 421 Login incorrect.

**Comment by T4y1oR** [comment]
这是fscan爆破错误日志。

**Comment by yeuwie** [comment]
> 这是fscan爆破错误日志。
为什么会报错呢

**Comment by yeuwie** [comment]
> 这是fscan爆破错误日志。

为什么会报错呢
