### ISSUE TITLE
RingQ.exe火绒直接查杀（2024-6-19）

### ISSUE THREAD

**Issue by githubb000** [T4y1oR/RingQ#30]
![image](https://github.com/T4y1oR/RingQ/assets/135519887/a4f71bea-77cf-40f3-8e15-ed1ec412b9b2)

![image](https://github.com/T4y1oR/RingQ/assets/135519887/c9bad336-74b8-441d-9eda-25e794397da5)

**Comment by T4y1oR** [comment]
![image](https://github.com/T4y1oR/RingQ/assets/85985129/cd4ba501-30ef-4783-9ffe-faa46c27864c)
![image](https://github.com/T4y1oR/RingQ/assets/85985129/da3b0c5e-437f-4de9-9a01-7b946d19fd46)
![image](https://github.com/T4y1oR/RingQ/assets/85985129/46e46b94-6499-4aba-b166-19fa6d9badfe)

物理机+服务器+虚拟机

**Comment by githubb000** [comment]
师傅我知道是什么原因了，从Releases版本下载下来的不是最新版，应该是版本没替换好。
![image](https://github.com/T4y1oR/RingQ/assets/135519887/eb61f79f-3656-43c6-acce-25f7282669b0)

![image](https://github.com/T4y1oR/RingQ/assets/135519887/efbaa911-f78a-429b-b469-6ebf0de841a5)
直接从code下载可以正常免杀
![image](https://github.com/T4y1oR/RingQ/assets/135519887/da79026d-3b78-4dfc-b766-5f41a39e8957)

**Comment by T4y1oR** [comment]
OK 我更新下。 如果对你有帮助的话 点个Star吧~  感谢
