### ISSUE TITLE
运行RingQ.exe后有黑窗口吗？

### ISSUE THREAD

**Issue by xiangyuanxuan** [T4y1oR/RingQ#33]
![Uploading 49.png…]()

**Comment by T4y1oR** [comment]
支持无黑框 
源码添加一行代码 重新编译即可。

`#pragma comment( linker, "/subsystem:\"windows\" /entry:\"mainCRTStartup\"" )`

**Comment by xiangyuanxuan** [comment]
可能是编译器版本的问题，编译后exe报毒
