### ISSUE TITLE
有点难受

### ISSUE THREAD

**Issue by YuHang-P** [T4y1oR/RingQ#35]
NPS内网穿透的客户端弄完之后,服务里面直接无法启动了

**Comment by T4y1oR** [comment]
![image](https://github.com/T4y1oR/RingQ/assets/85985129/cc2f9604-2da5-4993-b7bb-811a9b9796e9)
可以试一下 frp

**Comment by YuHang-P** [comment]
FRP不会部署,比较尴尬
