### ISSUE TITLE
360全家桶，赛门铁克，卡巴斯基，小红伞好像都过不了

### ISSUE THREAD

**Issue by whoami-juruo** [T4y1oR/RingQ#39]
![屏幕截图 2024-07-02 124500](https://github.com/T4y1oR/RingQ/assets/149454139/c0fd22a4-65c1-4c5d-ab50-ee4a2ab0d150)
![屏幕截图 2024-07-02 124018](https://github.com/T4y1oR/RingQ/assets/149454139/97525911-572f-4067-b58b-a208c3c2012a)
![屏幕截图 2024-07-02 123844](https://github.com/T4y1oR/RingQ/assets/149454139/e0c74134-c524-4c81-986b-df19ce42c2d2)
![屏幕截图 2024-07-02 123019](https://github.com/T4y1oR/RingQ/assets/149454139/b8f702c1-637f-4eb6-acbf-431297de96a3)

**Comment by Clay6413** [comment]
![屏幕截图 2024-07-02 124116](https://github.com/T4y1oR/RingQ/assets/149454139/2bd31135-8ef9-477e-bd66-4454628cff90)
