### ISSUE TITLE
这个缺点就是命令行持续弹出

### ISSUE THREAD

**Issue by 1764549853** [T4y1oR/RingQ#65]
命令行一直弹出 无法隐藏 虽然可以免杀和上线 但是不适合长期和潜伏 只适合过渡一下

**Comment by T4y1oR** [comment]
很早就解答了哦 最初设计场景就不是适用于权限维持和钓鱼等 你说的场景更适合dll劫持等
[issues3](https://github.com/T4y1oR/RingQ/issues/3)

**Comment by 1764549853** [comment]
好的，我找了很久的免杀，请问有没有什么适合我说的场景，有没有思路提供一下，谢谢，我不会任何语言的编程。免杀对我来说很吃力。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: T4y1oR ***@***.***&gt;
发送时间: 2024年8月7日 14:22
收件人: T4y1oR/RingQ ***@***.***&gt;
抄送: 1764549853 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [T4y1oR/RingQ] 这个缺点就是命令行持续弹出 (Issue #65)





 
很早就解答了哦 最初设计场景就不是适用于权限维持和钓鱼等 你说的场景更适合dll劫持等
 issues3
