### ISSUE TITLE
本地绝对路径加载失败

### ISSUE THREAD

**Issue by jx4321** [T4y1oR/RingQ#75]
师傅，使用时发现本地绝对路径加载main.txt时，被加载的程序没有运行，推测是没有找到文件，用的最新版本尝试也是同样的情况。
加载脚本如下：
![image](https://github.com/user-attachments/assets/2e471a1f-3b7a-44cf-9c60-24ba940dcd0b)
运行结果如下：
![image](https://github.com/user-attachments/assets/758a6504-1505-454f-bdc9-cb68d1e45ec4)

**Comment by T4y1oR** [comment]
已更新
